spring :
  thymeleaf :
    cache : false
    check-template-location : true
    prefix : /templates/
    suffix : .html
  profiles:
    active: local
    
mybatis:
  configuration:
    jdbc-type-for-null: "NULL"